projectio/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_f, name='login'),
    
]

projectio/core/urls.py
from django.urls import path 
from . import views

app_name='core'
#----------------------------------
urlpatterns=[
path('',views.index, name='index'),
path('about/',views.about, name='about'),
]

projectio/project/urls.py
from django.urls import path

from . import views

app_name = 'project'

#---------------------------------------------
urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name = 'edit'),
    path('<uuid:pk>/delete/', views.delete, name = 'delete'),
    path('<uuid:pk>/upload_file/', views.upload_file, name='upload_file'),
]

projectio/projectio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]

projectio/core/models.py
from django.db import models

# Create your models here.

projectio/core/views.py
from django.shortcuts import render

#----front page
def index(request):
    return render(request, 'core/index.html')

#---about page
def about(request):
    return render(request, 'core/about.html')

projectio/core/templates/core/about.html
{% extends 'core/base.html' %}
<!--  -->
{% block content %}
<!--  -->
<h1 class="text-3xl">ABOUT ProjectIO</h1>
<div class="space-y-6 mt-6">
  <p class="">
    Lorem FIRST ipsum dolor sit, amet consectetur adipisicing elit. Iure
    voluptas fuga sunt natus? Architecto impedit natus deleniti, delectus
    voluptatibus voluptate et vitae quos velit placeat non vero distinctio
    officia quibusdam?
  </p>
  <p class="">
    Lorem SECOND ipsum dolor sit, amet consectetur adipisicing elit. Iure
    voluptas fuga sunt natus? Architecto impedit natus deleniti, delectus
    voluptatibus voluptate et vitae quos velit placeat non vero distinctio
    officia quibusdam?
  </p>
</div>

<!--  -->
{% endblock %}

projectio/core/templates/core/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <!-- NavBar -->
    <nav class="py-6 px-8 flex items-center justify-between bg-slate-600">
      <h1 class="text-xl text-white">
        <a href="{% url 'core:index'%}">ProjectIO</a>
      </h1>
      <div class="space-x-4">
        <a href="{% url 'core:about'%}" class="text-white">About</a>

        <!-- login and signup -->
        {% if request.user.is_authenticated %}
        <a
          href="{% url 'project:projects'%}"
          class="py-4 px-8 bg-sky-500 text-white"
          >Projects</a
        >
        {% else %}
        <a
          href="{% url 'account:login' %}"
          class="py-4 px-8 bg-slate-500 text-white"
          >LogIn</a
        >
        <a
          href="{% url 'account:signup' %}"
          class="py-4 px-8 bg-sky-500 text-white"
          >SignUp</a
        >
        {% endif %}
      </div>
    </nav>
    <!-- NavBar end -->
    <!-- Main -->
    <main class="py-6 px-8">
      {% block content %}
      <!--  -->
      {% endblock %}
    </main>
    <!-- Main end-->

    <!-- Footer -->
    <footer class="py-8 px-8 bg-slate-700">
      <p class="text-white">Copyright (c) 2024 - Timmy&Co</p>
    </footer>
  </body>
</html>

projectio/core/templates/core/index.html
{% extends 'core/base.html' %}
<!--  -->
{% block content %}
<!--  -->
<header class="py-12 text-center">
  <h1 class="text-3xl">Welcome to ProjectIO</h1>
</header>

<!--  -->
{% endblock %}