projectio/core/urls.py
from django.urls import path 
from . import views

app_name='core'
#----------------------------------
urlpatterns=[
path('',views.index, name='index'),
path('about/',views.about, name='about'),
]

projectio/projectio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]

projectio/task/urls.py
from django.urls import path

from . import views

app_name='task'

urlpatterns =[
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.detail, name='detail'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

projectio/task/models.py
from django.db import models
import uuid

from account.models import User
from project.models import Project
from todolist.models import Todolist
# Create your models here.

class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    todolist = models.ForeignKey(Todolist, related_name='tasks', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True )
    is_done = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

projectio/task/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from project.models import Project
from todolist.models import Todolist 
from . models import Task
# Create your views here.

@login_required
def add(request, project_id, todolist_id):
    #-------Project--------------
    project =Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)

    if request.method =='POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        Task.objects.create(project=project, todolist=todolist, name=name, description=description, created_by=request.user)
        return redirect(f'/projects/{project_id}/{todolist_id}/')


    return render(request, 'task/add.html')


@login_required
def detail(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    if request.GET.get('is_done', '')=='yes':
        task.is_done=True
        task.save()

    return render(request, 'task/detail.html',{'task': task})


@login_required
def edit(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    if request.method =='POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        

        if name: 
            task.name = name

        task.description = description
        task.save()


        return redirect(f'/projects/{project_id}/{todolist_id}/{pk}/')
    
    return render(request, 'task/edit.html',{
        'task':task
    })


@login_required
def delete(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    task.delete()

    return redirect(f'/projects/{project_id}/{todolist_id}/')

projectio/task/templates/task/add.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">Add Task</h1>

<!-- List of projects -->
<form action="." method="post" class="mt-6 px-4 space-y-4">
  {% csrf_token %}

  <!-- Email -->
  <div>
    <label>Name</label><br />
    <input
      type="text"
      name="name"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    />
  </div>
  <!-- Password 1 -->
  <div>
    <label>Description</label><br />
    <textarea
      name="description"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    ></textarea>
  </div>
  <!-- Password 2 -->

  <!-- Button -->
  <div>
    <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
  </div>
</form>

<!--  -->
{% endblock %}

projectio/task/templates/task/detail.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">{{task.name}}:</h1>
<!--  -->
<p class="flex space-x-4 mb-3">
  <strong class="font-bold">Status:</strong>
  {% if task.is_done %}
  <!--  -->
  <a class="text-green-500" href="#"
    ><svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      class="size-6"
    >
      <path
        d="M7.493 18.5c-.425 0-.82-.236-.975-.632A7.48 7.48 0 0 1 6 15.125c0-1.75.599-3.358 1.602-4.634.151-.192.373-.309.6-.397.473-.183.89-.514 1.212-.924a9.042 9.042 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75A.75.75 0 0 1 15 2a2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H14.23c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23h-.777ZM2.331 10.727a11.969 11.969 0 0 0-.831 4.398 12 12 0 0 0 .52 3.507C2.28 19.482 3.105 20 3.994 20H4.9c.445 0 .72-.498.523-.898a8.963 8.963 0 0 1-.924-3.977c0-1.708.476-3.305 1.302-4.666.245-.403-.028-.959-.5-.959H4.25c-.832 0-1.612.453-1.918 1.227Z"
      />
    </svg>
  </a>

  {% else %}
  <!--  -->
  <a href="#"
    ><svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      class="size-6"
    >
      <path
        d="M21.731 2.269a2.625 2.625 0 0 0-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 0 0 0-3.712ZM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 0 0-1.32 2.214l-.8 2.685a.75.75 0 0 0 .933.933l2.685-.8a5.25 5.25 0 0 0 2.214-1.32l8.4-8.4Z"
      />
      <path
        d="M5.25 5.25a3 3 0 0 0-3 3v10.5a3 3 0 0 0 3 3h10.5a3 3 0 0 0 3-3V13.5a.75.75 0 0 0-1.5 0v5.25a1.5 1.5 0 0 1-1.5 1.5H5.25a1.5 1.5 0 0 1-1.5-1.5V8.25a1.5 1.5 0 0 1 1.5-1.5h5.25a.75.75 0 0 0 0-1.5H5.25Z"
      />
    </svg>
  </a>
  <!--  -->

  {% endif %}
</p>
<!--  -->
{% if task.description %}
<p class="mb-6">{{task.description}}</p>
{% endif %}
<!--  -->
{% if not task.is_done %}
<a href="?is_done=yes" class="py-4 px-8 text-white bg-emerald-600 inline-block"
  >Click is Done</a
>
{% endif %}
<a
  href="{% url 'task:edit' task.project_id task.todolist_id task.id    %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
  >Edit Task</a
>
<a
  href="{% url 'task:delete' task.project_id task.todolist_id task.id    %}"
  class="py-4 px-8 bg-red-500 text-white inline-block"
  >Delete</a
>

<!--  -->
{% endblock %}

<!-- 



<div class="mt-6 grid grid-cols-4 gap-4">

  {% for task in todolist.tasks.all %}
  <div class="py-6 px-6 bg-slate-200">
    <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}">
      <h2 class="mb-4 text-xl">{{task.name}}</h2>
      <p class="text-sm text-slate-600">{{task.description}}</p>
    </a>
  </div>

  {% endfor %}
</div>




-->

projectio/task/templates/task/edit.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">Add Task</h1>

<!-- List of projects -->
<form action="." method="post" class="mt-6 px-4 space-y-4">
  {% csrf_token %}

  <!-- Email -->
  <div>
    <label>Name</label><br />
    <input
      type="text"
      value="{{task.name}}"
      name="name"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    />
  </div>
  <!-- Password 1 -->
  <div>
    <label>Description</label><br />
    <textarea
      name="description"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    >
{{task.description}}</textarea
    >
  </div>
  <!-- Password 2 -->

  <!-- Button -->
  <div>
    <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
  </div>
</form>

<!--  -->
{% endblock %}