projectio/core/urls.py
from django.urls import path 
from . import views

app_name='core'
#----------------------------------
urlpatterns=[
path('',views.index, name='index'),
path('about/',views.about, name='about'),
]

projectio/project/urls.py
from django.urls import path

from . import views

app_name = 'project'

#---------------------------------------------
urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name = 'edit'),
    path('<uuid:pk>/delete/', views.delete, name = 'delete'),
    path('<uuid:pk>/upload_file/', views.upload_file, name='upload_file'),
]

projectio/projectio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]

projectio/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'



urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todo_list, name='todolist'),
    path('<uuid:pk>/edit', views.edit, name='edit'),
    path('<uuid:pk>/delete', views.delete, name='delete'),

]

projectio/project/models.py
from django.db import models
import uuid

from account.models import User


#-------- project -----------
class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

# File model

class ProjectFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='files', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    attachment = models.FileField(upload_to='projectfiles')
    

    def __str__(self):
        return self.name
    

projectio/project/forms.py
from django.forms import ModelForm

from .models import ProjectFile


class ProjectFileForm(ModelForm):
    class Meta:
        model = ProjectFile
        fields = {'name', 'attachment',}

projectio/project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Project
from .forms import ProjectFileForm

# Create your views here.

@login_required
def projects(request):
    projects = Project.objects.filter(created_by=request.user)
    return render(request, 'project/projects.html',{'projects':projects})

@login_required
def project(request, pk):
    project = Project.objects.filter(created_by = request.user).get(pk=pk)

    return render(request, 'project/project.html',{'project':project})


@login_required
def add(request):
    if request.method=='POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Project.objects.create(name=name, description=description, created_by=request.user)

            return redirect('/projects/')
        else:
            print('Not valid data')

    return render(request, 'project/add.html')


@login_required
def edit(request, pk):
    project = Project.objects.filter(created_by = request.user).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            project.name = name
            project.description = description
            project.save()

            return redirect('/projects/')
        
    return render(request, 'project/edit.html',{'project':project})


@login_required
def delete(request, pk):
    project = Project.objects.filter(created_by = request.user).get(pk=pk)
    project.delete()
    
    return redirect('/projects/')


@login_required
def upload_file(request, pk):
    project = Project.objects.filter(created_by = request.user).get(pk=pk)

    if request.method=='POST':
        form =ProjectFileForm(request.POST, request.FILES)

        if form.is_valid():
            projectfile=form.save(commit=False)
            projectfile.project=project
            projectfile.save()

            return redirect(f'/projects/{pk}/')
    else:
        form = ProjectFileForm()

    return render(request, 'project/upload_file.html', {
        "project":project,
        "form":form
        })

projectio/project/templates/project/add.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">Add Project</h1>

<!-- List of projects -->
<form action="." method="post" class="mt-6 px-4 space-y-4">
  {% csrf_token %}

  <!-- Email -->
  <div>
    <label>Name</label><br />
    <input
      type="text"
      name="name"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    />
  </div>
  <!-- Password 1 -->
  <div>
    <label>Description</label><br />
    <textarea
      name="description"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    ></textarea>
  </div>
  <!-- Password 2 -->

  <!-- Button -->
  <div>
    <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
  </div>
</form>

<!--  -->
{% endblock %}

projectio/project/templates/project/edit.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">Edit Project</h1>

<!-- List of projects -->
<form action="." method="post" class="mt-6 px-4 space-y-4">
  {% csrf_token %}

  <!-- Email -->
  <div>
    <label>Name</label><br />
    <input
      type="text"
      name="name"
      value="{{project.name}}"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    />
  </div>
  <!-- Password 1 -->
  <div>
    <label>Description</label><br />
    <textarea
      name="description"
      class="w-full py-4 px-6 bg-slate-400 text-white"
    >
{{project.description}}</textarea
    >
  </div>
  <!-- Password 2 -->

  <!-- Button -->
  <div>
    <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
  </div>
</form>

<!--  -->
{% endblock %}

projectio/project/templates/project/project.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">{{project.name}}:</h1>

{% if project.description %}
<p class="mb-6">{{project.description}}</p>
{% endif %}

<a
  href="{% url 'todolist:add' project.id %}"
  class="py-4 px-8 text-white bg-emerald-600 inline-block"
  >Add todolist</a
>
<a
  href="{% url 'project:upload_file' project.id %}"
  class="py-4 px-8 text-white bg-slate-600 inline-block"
  >Upload File</a
>
<a
  href="{% url 'project:edit' project.id %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
  >Edit</a
>
<a
  href="{% url 'project:delete' project.id %}"
  class="py-4 px-8 bg-red-500 text-white inline-block"
  >Delete</a
>
<h3 class="mb-6 mt-5 text-2xl">TodoLists:</h3>
<!-- List of projects -->
<div class="mt-6 grid grid-cols-4 gap-4">
  <!-- Project Window -->
  {% for todolist in project.todolists.all %}
  <div class="py-6 px-6 bg-slate-200">
    <a href="{% url 'todolist:todolist' project.id todolist.id %}">
      <h3 class="mb-4 text-xl">{{todolist.name}}</h3>
      <p class="text-sm text-slate-600">{{todolist.description}}</p>
    </a>
  </div>
  <!-- Project window END-->
  {% endfor %}
</div>
<h3 class="mb-6 mt-5 text-2xl">Files:</h3>
<div class="mt-6 grid grid-cols-4 gap-4">
  {% for projectfile in project.files.all %}
  <!--  -->
  <div class="py-6 px-6 bg-slate-200">
    <h3 class="mb-4 text-xl">{{projectfile.name}}</h3>
    <a
      href="{% projectfile.attachment.url %}"
      target="_blank"
      class="text-sm text-slate-600"
      >Download file</a
    >
  </div>
  <!--  -->
  {% endfor %}
</div>
<!--  -->
{% endblock %}

projectio/project/templates/project/projects.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">Projects:</h1>
<a
  href="{% url 'project:add' %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
  >Add project</a
>
<!-- List of projects -->
<div class="mt-6 grid grid-cols-4 gap-4">
  <!-- Project Window -->
  {% for project in projects%}
  <div class="py-6 px-6 bg-slate-200">
    <a href="{% url 'project:project' project.id %}">
      <h2 class="mb-4 text-xl">{{project.name}}</h2>
      <p class="text-sm text-slate-600">{{project.description}}</p>
    </a>
  </div>
  <!-- Project window END-->
  {% endfor %}
</div>

<!--  -->
{% endblock %}

projectio/project/templates/project/upload_file.html
{% extends 'core/base.html'%}
<!--  -->
{% block content %}
<!--  -->
<h1 class="mb-6 text-3xl">Upload file to <strong>{{project.name}}</strong>:</h1>
<!--  -->

<form
  method="post"
  action="."
  enctype="multipart/form-data"
  class="mt-6 px-4 space-y-4"
>
  {% csrf_token %}
  <!--  -->
  {{form.as_p}}
  <div>
    <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
  </div>
</form>

<!--  -->
{% endblock %}